[example] Fix "@zeit/next-typescript" dependency missing (#16603)
Error: Cannot find module '@zeit/next-typescript/babel' from '~/nextjs-with-typescript'
    at Array.map (<anonymous>)